# -*- coding: utf-8 -*-
"""Interação com o usuário

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnHdNMSUtml5vqr3YXypfPOm889uwwy3

##Visualização de Variáveis e Textos
"""

print("Conhecendo o comando Print")

x = 8
print('x')

y = 10
  soma = x + y
  print(soma)

nome = 'Alessandro Silva'
print(nome)

"""Concatenação"""

x = 5
print('O valor de x é' , x)  #Juntar o texto na mesma linha da variável

print('O valor de x é' , x, 'e o dobro é' , x * 2)

print('Eu,', nome, 'tirei', x, 'na prova de Python')

y = 10; z = 20 + x - y

print('Declarar várias variáveis na mesma linha:', y, z)

"""Type"""

x = 10
type(x)
print('x', type (x))

nome = 'Alessandro'
print('nome', type(nome))

num = '100'
num_convert = int(num) # Converter variável
print('num', type(num))
print('num_conver', type(num_convert))

num_float = float(num)
print('num_float', num_float)

"""**Input**

*   Armazenar a informação digitada pelo usuário em uma variável
*   O dado armazenado sempre será um texto



"""

nome = input("Digite o nome do usuário ") #Aguarda o usuário digitar algo
print(nome)

valor = input('Digite a nota ')

print(nome, 'sua nota foi', valor)

valor = input('Digite o valor do produto: ')
print(valor)

desconto = int(valor) - 19
print(desconto)